  export const dummyRestaurants = [
    {
      id: 3,
      latitude: 37.5,
      longitude: 127.03,
      name: "효자동쌀국수미",
      category: "베트남",
      address: "서울시 강남구",
      distance: 0.26,
      reviewCount: 10,
      averageRating: 4.5,
      imageUrl: null
    },
    {
        id: 4,
        latitude: 37.45,
        longitude: 129.055969,
        name: "ZAMZAM",
        category: "기타",
        address: "경기도 화성시 3.1만세로 1130",
        distance: 0.23,
        reviewCount: 30,
        averageRating: 4.23,
        imageUrl: null
      },
      {
        id: 5,
        name: "효자동쌀국수미",
        category: "베트남",
        address: "경상북도 포항시 남구 희망대로 1233",
        weekdays: "정보없음",
        weekend: "정보없음",
        averageRating: 5.0,
        reviewCount: 1,
      },
      {
        id: 6,
        name: "샘플레스토랑",
        category: "일식",
        address: "서울시 강남구",
        weekdays: "09:00 - 18:00",
        weekend: "10:00 - 16:00",
        averageRating: 4.5,
        reviewCount: 10,
      },
      {
        id: 7,
        name: "샘플레스토랑",
        category: "일식",
        address: "서울시 강남구",
        weekdays: "09:00 - 18:00",
        weekend: "10:00 - 16:00",
        averageRating: 4.5,
        reviewCount: 10,
      },
  ];
